V 15.0.6 :: Add NewRelic middleware
alanszp/js-utils pull request #105
Opened 2024-07-05 19:54 UTC by ThomasDeferr

2024-07-05 20:52 UTC, fedekiwo commented
Agregate changelog!

2024-07-05 21:07 UTC, fedekiwo commented on CHANGELOG.md
> +
copiaste y pecaste jajaj

2024-07-05 21:11 UTC, alanszp requested changes

2024-07-05 21:11 UTC, alanszp commented on packages/express/package.json
> +  "version": "15.1.0",
esto no hay que actualizar, lo hace solo nuestro amigo lerna

2024-07-05 21:11 UTC, alanszp commented on packages/express/src/middlewares/configureNewRelic.ts
> +export function configureNewRelic(
no es mejor agregar esto al middleware que hace el call para crear el lifecycle? mas que nada para no estar repitiendolo en todos lados.
De ultima que la instancia de newrelic se pase como un param en este otro midleware, y si viene lo setiemos, sino nop

2024-07-05 21:12 UTC, alanszp commented on packages/express/src/middlewares/configureNewRelic.ts
> +export function configureNewRelic(
mismo hay que agregarlo en la de las lambdas!

2024-07-08 13:29 UTC, fedekiwo commented on packages/express/src/middlewares/configureNewRelic.ts
> +export function configureNewRelic(
el de las lambdas lo dejaría para cuándo lo implementemos ahí, porque capaz lo agregamos ahora y algo se nos caga

2024-07-08 19:28 UTC, fedekiwo approved these changes

2024-07-08 19:29 UTC, merged