Add API KEY logic for eventbridge requests
alanszp/js-utils pull request #25
Opened 2022-08-22 20:28 UTC by santiagomlorenzo

2022-08-25 16:58 UTC, alanszp requested changes

2022-08-25 16:58 UTC, alanszp commented on packages/express/src/middlewares/authWithJWT.ts
> +interface TokenOptions {
este lo escribi mal yo
```suggestion
interface ApiKeyOptions {
```

2022-08-25 16:58 UTC, alanszp commented on packages/express/src/middlewares/authWithJWT.ts
> +  validTokens: string[];
```suggestion
  validApiKeys: string[];
```

2022-08-25 16:58 UTC, alanszp commented on packages/express/src/middlewares/authWithJWT.ts
> +  publicKey: string,
esta publicKey tiene que estar dentro de las options de JWT

2022-08-25 16:58 UTC, alanszp commented on packages/express/src/middlewares/authWithJWT.ts
> +          org: "0",
```suggestion
          org: "0", --> Aca tendrias que tomar la org que viene en el request
```

2022-08-25 16:58 UTC, alanszp commented on packages/express/src/middlewares/authWithJWT.ts
> +          organizationReference: "none",
esto rompe en todos lados, tiene que ser la org posta que le pertenece al req

2022-08-25 16:58 UTC, alanszp commented on packages/express/src/middlewares/authWithJWT.ts
> +          organizationReference: "none",
es complicado como le pasamos la org

2022-08-25 17:01 UTC, alanszp requested changes

2022-08-25 17:01 UTC, alanszp commented on packages/express/src/middlewares/authWithJWT.ts
> +        logger.info("auth.authWithJwt.invalidJwt", { jwt, error });
logs tienen jwt todavia

2022-08-25 18:16 UTC, santiagomlorenzo commented on packages/express/src/middlewares/authWithJWT.ts
> +interface TokenOptions {
y yo me olvide de cambiarlo

2022-08-25 18:24 UTC, santiagomlorenzo commented on packages/express/src/middlewares/authWithJWT.ts
> +        const authAttempts = authMethods.map((method) =>
pasa que hay una diferencia entre undefined y null, undefined es cuando no hay token y null cuando fallo en autenticar, si no nos importa esa diferencia, compacto e larray directo. Si nos importa diferenciar, compacto solo para ahorrarme el find final

2022-08-25 23:09 UTC, alanszp approved these changes

2022-08-25 23:09 UTC, alanszp commented on packages/express/src/middlewares/authenticateUser.ts
> +  return function getMiddlewareForMethods(authMethods: Options["types"]) {
Detecte un error! si no ponemos esto, cuando se defina el tipo [AuthMethods.JWT, AuthMethods.API_KEY],

cuando se llame, no te va a dejar llamar de esta manera: getMiddlewareForMethods([AuthMethods.API_KEY]) y a que pide que si o si sean los dos en ese orden. (lo probe en local). DE esta manera hace que funque todo!


```suggestion
  return function getMiddlewareForMethods(authMethods: Options["types"][number][]) {
```

2022-08-26 20:43 UTC, alanszp approved these changes

2022-08-31 21:05 UTC, merged