Add NotificationInputParams
alanszp/js-utils pull request #27
Opened 2022-09-08 16:01 UTC by canofm

### What's new?

- Interface and class for Notification spread through the AWS Event Bridge

2022-09-08 16:56 UTC, alanszp requested changes

2022-09-08 16:56 UTC, alanszp commented on packages/eventbridge-client/src/NotificationInput.ts
> +  public detailType: NotificationDetailType;
la llamaria topic para que sea un numbre nuestro

2022-09-08 16:56 UTC, alanszp commented on packages/eventbridge-client/src/NotificationDetailTypes.ts
> +  EMPLOYEE_UPDATED = "employee.updated",
no pondria un enum aca todavia. mas que nada para no tener que estar updateando esta lib x cada nuevo evento que hagamos. Esto nos va a traer potenciales dolores de cabeza, poreso dijimos que quede mas del lado del cliente por ahora

2022-09-08 16:56 UTC, alanszp commented on packages/eventbridge-client/src/NotificationInput.ts
> +type Detail<T> = FixedDetail<T> & T;
el type que tiene hoy en dia es mas "generico" es:
```suggestion
type Detail = Record<string, unknown>;
```

Si queres definirle un tipo, al genericl podriamos ponerle:

```ts
export interface NotificationInputParams<T extends Record<string, unknown> = Record<string, unknown>> {
```

2022-09-09 17:41 UTC, santiagomlorenzo approved these changes
LGTM. Lo unico que semanticamente me hace un poco de ruido tener un input aca, pero entiendo la necesidad de un input generico de este estilo y no se me ocurre otro lugar para ponerlo. @alanszp opiniones?

2022-09-09 19:18 UTC, alanszp approved these changes

2022-09-09 19:18 UTC, merged